#!/bin/bash
wget https://raw.githubusercontent.com/GreatMedivack/files/master/list.out &>/dev/null
if [ $? -ne 0 ]; then
echo "Error then download report file"
exit 2
fi
if [[ $1 = "" ]]
then
server=LOG
else
server=$1
fi
datainname=$(date +%d_%m_%y)
grep '\(Error\|CrashLoopBackOff\)' list.out | awk '{print $1}' > $server"_"$datainname"_failed.out"
grep 'Running' list.out | awk '{print $1}' > $server"_"$datainname"_running.out"
sed -ri 's/\-[a-z0-9]{4,}+\-.[^\-]+$//g' $server"_"$datainname"_failed.out" # Если нужны срабатывания на demomed-init-job-vsgjv, удалить{4,}
sed -ri 's/\-[a-z0-9]{4,}+\-.[^\-]+$//g' $server"_"$datainname"_running.out"
install -m 444 <(echo -e "- Количество работающих сервисов: `wc -l $server"_"$datainname"_running.out"| awk '{print $1}'`\n
- Количество сервисов с ошибками: `wc -l $server"_"$datainname"_failed.out" | awk '{print $1}'`\n
- Имя системного пользователя: `echo $USER`\n
- Дата: `date +%x` ") $server"_"$datainname"_report.out"
mkdir -p arhives 
tar -zcf $server"_"$datainname $server"_"$datainname"_report.out" $server"_"$datainname"_failed.out" $server"_"$datainname"_running.out" # if need list.out just add them
mv -n $server"_"$datainname ./arhives #???? if arhive exist and broken?????
rm -f *.out $server"_"$datainname 2>/dev/null # !!!ACHTUNG!!! DELETE ALL FILES *.out!
tar -xOf ./arhives/$server"_"$datainname &> /dev/null # test arhive even if it exist
if [ $? -ne 0 ]; then
echo "Error in arhive file"
exit 1
else
echo "No error"
exit 0
fi
