#!/bin/bash
wget --timeout=15 https://raw.githubusercontent.com/GreatMedivack/files/master/list.out &>/dev/null || { echo -e "\e[31mError in wget\e[0m" && exit 2; }  
datainname=$(date +%d_%m_%y)
grep '\(Error\|CrashLoopBackOff\)' list.out | awk '{print $1}' | sed -r 's/\-[a-z0-9]{4,}+\-.[^\-]+$//g' > ${1:-log}"_"$datainname"_failed.out"
grep 'Running' list.out | awk '{print $1}' | sed -r 's/\-[a-z0-9]{4,}+\-.[^\-]+$//g' > ${1:-log}"_"$datainname"_running.out" # Если нужны срабатывания на demomed-init-job-vsgjv, удалить{4,}
install -m 444 <(echo -e "- Количество работающих сервисов: `wc -l ${1:-log}"_"$datainname"_running.out"| awk '{print $1}'`\n
- Количество сервисов с ошибками: `wc -l ${1:-log}"_"$datainname"_failed.out" | awk '{print $1}'`\n
- Имя системного пользователя: `echo $USER`\n
- Дата: `date +%x` ") ${1:-log}"_"$datainname"_report.out"
mkdir -p arhives 
tar -zcf ${1:-log}"_"$datainname ${1:-log}"_"$datainname"_report.out" ${1:-log}"_"$datainname"_failed.out" ${1:-log}"_"$datainname"_running.out" # if need list.out just
mv -n ${1:-log}"_"$datainname ./arhives #???? if arhive exist and broken?????
rm -f *.out ${1:-log}"_"$datainname 2>/dev/null # !!!ACHTUNG!!! DELETE ALL FILES *.out!
tar -xOf ./arhives/${1:-log}"_"$datainname &> /dev/null || { echo -e "\e[31mError in arhive file\e[0m" && exit 1; } # test arhive even if it exist
echo -e "\e[42mNo error\e[0m"
exit 0
